// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigGet(arg1:string):Promise<string>;

export function ReadFile():Promise<main.ReadFileOutput>;

export function SaveFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<boolean>;
